version: "3.9"

services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.8-management-alpine
    domainname: rabbitmq.com
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=root
      - RABBITMQ_USERNAME=admin
      - RABBITMQ_PASSWORD=admin
    ports:
        # AMQP protocol port
        - '5672:5672'
        # HTTP management UI
        - '15672:15672'
    volumes:
        - ./rabbitmq/log/:/var/log/rabbitmq/
        - ./rabbitmq/data/:/var/lib/rabbitmq/
    networks:
      - rabbitmq_network

  db_rides:
    image: postgres
    volumes:
      - ./TraWell-rides/postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"
    networks:
      - rabbitmq_network

  web_rides:
    build:
        context: "./TraWell-rides"
        dockerfile: Dockerfile
    restart: on-failure
    command: bash -c "pip install -r requirements.txt && python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8001"
    volumes:
        - ./TraWell-rides:/rides
    ports:
        - "8001:8001"
    depends_on:
        - db_rides
        - rabbitmq
    networks:
        - rabbitmq_network

  worker_rides:
      build:
        context: "./TraWell-rides"
        dockerfile: Dockerfile
      restart: on-failure
      command:  bash -c "celery --app rides_microservice.celery.app worker --loglevel=INFO -E -Q archive_queue"
      volumes:
          - ./TraWell-rides:/rides
      depends_on:
        - web_rides
        - rabbitmq
        - db_rides
      networks:
        - rabbitmq_network

  db_users:
    image: postgres
    volumes:
      - ./TraWell-users/postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5435:5432"
    networks:
      - rabbitmq_network

  web_users:
    build:
        context: ./TraWell-users
        dockerfile: Dockerfile
    restart: on-failure
    command: bash -c "pip install -r requirements.txt && python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8003"
    volumes:
      - ./TraWell-users:/users
    ports:
      - "8003:8003"
    depends_on:
      - db_users
      - rabbitmq
    networks:
      - rabbitmq_network

  worker_users:
    build:
      context: "./TraWell-users"
      dockerfile: Dockerfile
    restart: on-failure
    command:  bash -c "celery --app users_service.celery.app worker --loglevel=INFO -E"
    volumes:
        - ./TraWell-users:/users
    depends_on:
      - web_users
      - rabbitmq
      - db_users
    networks:
      - rabbitmq_network


  db_reviews:
    image: postgres
    volumes:
      - ./TraWell-reviews/postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5436:5432"
    networks:
      - rabbitmq_network

  web_reviews:
    build:
      context: ./TraWell-reviews
      dockerfile: Dockerfile
    restart: on-failure
    command: bash -c "pip install -r requirements.txt && python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8004"
    volumes:
      - ./TraWell-reviews:/reviews
    ports:
      - "8004:8004"
    depends_on:
      - db_reviews
      - rabbitmq
    networks:
      - rabbitmq_network

  worker_reviews:
    build:
      context: "./TraWell-reviews"
      dockerfile: Dockerfile
    restart: on-failure
    command: bash -c "celery --app reviews_service.celery.app worker --loglevel=INFO -E"
    volumes:
      - ./TraWell-reviews:/reviews
    depends_on:
      - web_reviews
      - rabbitmq
      - db_reviews
    networks:
      - rabbitmq_network


  db_notifications:
    image: postgres
    volumes:
      - ./TraWell-notifications/postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5437:5432"
    networks:
      - rabbitmq_network

  web_notifications:
    build:
        context: ./TraWell-notifications
        dockerfile: Dockerfile
    restart: on-failure
    command: bash -c "pip install -r requirements.txt && python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8007"
    volumes:
      - ./TraWell-notifications:/notifications
    ports:
      - "8007:8007"
    depends_on:
      - db_notifications
      - rabbitmq
    networks:
      - rabbitmq_network

  worker_notifications:
    build:
      context: "./TraWell-notifications"
      dockerfile: Dockerfile
    restart: on-failure
    command:  bash -c "celery --app notify_microservice.celery.app worker --loglevel=INFO"
    volumes:
        - ./TraWell-notifications:/notifications
    depends_on:
      - db_notifications
      - web_notifications
      - rabbitmq
    networks:
      - rabbitmq_network

  db_history:
    image: postgres
    volumes:
      - ./TraWell-history/postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5439:5432"
    networks:
      - rabbitmq_network

  web_history:
    build:
      context: ./TraWell-history
      dockerfile: Dockerfile
    restart: on-failure
    command: bash -c "pip install -r requirements.txt && python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8002"
    volumes:
      - ./TraWell-history:/history
    ports:
      - "8002:8002"
    depends_on:
      - db_history
      - rabbitmq
    networks:
      - rabbitmq_network

  worker_history:
    build:
      context: "./TraWell-history"
      dockerfile: Dockerfile
    restart: on-failure
    command: bash -c "celery --app history_microservice.celery.app worker --loglevel=INFO"
    volumes:
      - ./TraWell-history:/history
    depends_on:
      - db_history
      - web_history
      - rabbitmq
    networks:
      - rabbitmq_network

  beat:
    build:
      context: "./TraWell-rides"
      dockerfile: Dockerfile
    restart: on-failure
    command: bash -c "celery --app rides_microservice.celery.app beat --loglevel=INFO"
    volumes:
      - ./TraWell-rides:/rides
    depends_on:
      - db_rides
      - web_rides
      - rabbitmq
      - worker_rides
    networks:
      - rabbitmq_network

  db_keycloak:
      container_name: db_keycloak
      image: postgres:latest
      user: root
      ports:
        - "5432:5432"
      volumes:
        - ./TraWell-KrakenD/postgres_data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: password
  web_keycloak:
      build:
        context: "./TraWell-KrakenD"
        dockerfile: Dockerfile
      image: jboss/keycloak:16.1.1
      ports:
        - "8403:8080"
      environment:
        DB_VENDOR: POSTGRES
        DB_ADDR: db_keycloak
        DB_DATABASE: keycloak
        DB_USER: keycloak
        DB_PASSWORD: password
        DB_SCHEMA: public
        DB_PORT: 5432
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: password
        KEYCLOAK_IMPORT: /tmp/config/keycloak/realms/trawell.json
        KEYCLOAK_FEATURES: 'declarative_user_profile'
        JAVA_OPTS_APPEND: "-Dkeycloak.profile.feature.upload_scripts=enabled -Dkeycloak.profile.feature.declarative_user_profile=enabled"
      volumes:
      - type: bind
        source: ./TraWell-KrakenD/config/keycloak/realms
        target: /tmp/config/keycloak/realms
      - type: bind
        source: ./TraWell-KrakenD/themes/custom
        target: /opt/jboss/keycloak/themes/custom
      depends_on:
        - db_keycloak
  krakend:
      build:
        context: "./TraWell-KrakenD"
        dockerfile: Dockerfile
      image: devopsfaith/krakend:latest
      command: run -d -c /etc/krakend/krakend.json
      ports:
        - "9000:9000"
      volumes:
        - ./TraWell-KrakenD/gateway:/etc/krakend

networks:
  rabbitmq_network:
    driver: bridge

volumes:
  postgres_data:

