version: "3.8"

services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.8-management-alpine
    domainname: rabbitmq.com
    environment:
        - RABBITMQ_DEFAULT_USER=admin
        - RABBITMQ_DEFAULT_PASS=password
        - AMQP_SERVER_URL=amqp://guest:guest@rabbitmq:5672
    ports:
        # AMQP protocol port
        - '5672:5672'
        # HTTP management UI
        - '15672:15672'
    volumes:
        - ./rabbitmq/log/:/var/log/rabbitmq/

#   celery:
#       image: calc-addition
#       build:
#           context: .
#           dockerfile: ./addition/Dockerfile
#       links:
#           - rabbit
#       deploy:
#           replicas: 2
#           restart_policy:
#               condition: on-failure
