version: "3.9"

services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.8-management-alpine
    domainname: rabbitmq.com
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=root
      - RABBITMQ_USERNAME=admin
      - RABBITMQ_PASSWORD=admin
    ports:
        # AMQP protocol port
        - '5672:5672'
        # HTTP management UI
        - '15672:15672'
    volumes:
        - ./rabbitmq/log/:/var/log/rabbitmq/
        - ./rabbitmq/data/:/var/lib/rabbitmq/
    networks:
      - rabbitmq_network

  db_rides:
    image: postgres
    volumes:
      - ./TraWell-rides/postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"
    networks:
      - rabbitmq_network

  web_rides:
    build:
        context: "./TraWell-rides"
        dockerfile: Dockerfile
    restart: on-failure
    command: bash -c "pip install -r requirements.txt && python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8001"
    volumes:
        - ./TraWell-rides:/rides
    ports:
        - "8001:8001"
    depends_on:
        - db_rides
        - rabbitmq
        # - worker_rides
    networks:
        - rabbitmq_network

  worker_rides:
      build:
        context: "./TraWell-rides"
        dockerfile: Dockerfile
      restart: on-failure
      command:  bash -c "celery --app rides_microservice.celery.app worker --loglevel=INFO -E"
      volumes:
          - ./TraWell-rides:/rides
      depends_on:
        - web_rides
        - rabbitmq
        - db_rides
      networks:
        - rabbitmq_network

  db_users:
    image: postgres
    volumes:
      - ./TraWell-users/postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5435:5432"
    networks:
      - rabbitmq_network

  web_users:
    build:
        context: ./TraWell-users
        dockerfile: Dockerfile
    restart: on-failure
    command: bash -c "pip install -r requirements.txt && python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8003"
    volumes:
      - ./TraWell-users:/users
    ports:
      - "8003:8003"
    depends_on:
      - db_users
      - rabbitmq
      # - worker_users
    networks:
      - rabbitmq_network
 
  worker_users:
    build:
      context: "./TraWell-users"
      dockerfile: Dockerfile
    restart: on-failure
    command:  bash -c "celery --app users_service.celery.app worker --loglevel=INFO -E"
    volumes:
        - ./TraWell-users:/users
    depends_on:
      - web_users
      - rabbitmq
      - db_users
    networks:
      - rabbitmq_network

  db_notifications:
    image: postgres
    volumes:
      - ./TraWell-notifications/postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5437:5432"
    networks:
      - rabbitmq_network

  web_notifications:
    build:
        context: ./TraWell-notifications
        dockerfile: Dockerfile
    restart: on-failure
    command: bash -c "pip install -r requirements.txt && python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8007"
    volumes:
      - ./TraWell-notifications:/notifications
    ports:
      - "8007:8007"
    depends_on:
      - db_notifications
      - rabbitmq
      # - worker_notifications
    networks:
      - rabbitmq_network

  worker_notifications:
    build:
      context: "./TraWell-notifications"
      dockerfile: Dockerfile
    restart: on-failure
    command:  bash -c "celery --app notify_microservice.celery.app worker --loglevel=INFO"
    volumes:
        - ./TraWell-notifications:/notifications
    depends_on:
      - db_notifications
      - web_notifications
      - rabbitmq
    networks:
      - rabbitmq_network

networks:
  rabbitmq_network:
    driver: bridge

volumes:
  postgres_data:

